import React from 'react';
import { Card } from '@/components/ui/card';
import { ArrowUpRight } from 'lucide-react';
const NutritionLandingPage = () => {
    return (React.createElement("div", { className: "min-h-screen bg-white" },
        React.createElement("nav", { className: "flex items-center justify-between p-6" },
            React.createElement("div", { className: "flex items-center space-x-2" },
                React.createElement("div", { className: "w-8 h-8 bg-green-600 rounded-full flex items-center justify-center" },
                    React.createElement("div", { className: "w-4 h-4 text-white" }, "\uD83C\uDF3F"))),
            React.createElement("div", { className: "flex space-x-6" },
                React.createElement("button", { className: "text-gray-600 hover:text-gray-900" }, "Home"),
                React.createElement("button", { className: "text-gray-600 hover:text-gray-900" }, "Product"),
                React.createElement("button", { className: "text-gray-600 hover:text-gray-900" }, "Shop"))),
        React.createElement("div", { className: "container mx-auto px-6 py-12 grid grid-cols-1 lg:grid-cols-2 gap-12" },
            React.createElement("div", { className: "space-y-6" },
                React.createElement("h1", { className: "text-6xl font-bold leading-tight" },
                    "We Take Care About Your",
                    ' ',
                    React.createElement("span", { className: "text-green-400" }, "Health")),
                React.createElement("p", { className: "text-gray-600" }, "Make sure your daily nutrition is sufficient. Consult your problem about nutrition with us."),
                React.createElement("div", { className: "flex items-center space-x-4" },
                    React.createElement("button", { className: "bg-black text-white px-6 py-3 rounded-full hover:bg-gray-800" }, "Get Started"),
                    React.createElement("div", { className: "w-12 h-12 rounded-full bg-gray-200" }),
                    React.createElement("button", { className: "p-2 rounded-full border border-gray-200" },
                        React.createElement(ArrowUpRight, { className: "w-5 h-5" }))),
                React.createElement("div", { className: "flex flex-wrap gap-3 pt-6" }, ['Nutrition', 'Supplements', 'Vitamins', 'Healthy Food', 'Consultation'].map((tag) => (React.createElement("span", { key: tag, className: "px-4 py-2 rounded-full border border-gray-200 text-gray-600 hover:border-gray-400 cursor-pointer" }, tag))))),
            React.createElement(Card, { className: "relative bg-green-100 rounded-3xl overflow-hidden" },
                React.createElement("div", { className: "absolute inset-0 grid grid-cols-3 grid-rows-3 gap-4 p-6" }, Array(9).fill(null).map((_, i) => (React.createElement("div", { key: i, className: "bg-white/20 rounded-lg" })))),
                React.createElement("div", { className: "absolute bottom-8 left-8 bg-white rounded-full px-6 py-3 flex items-center space-x-3" },
                    React.createElement("div", { className: "w-10 h-10 rounded-full bg-gray-200" }),
                    React.createElement("div", null,
                        React.createElement("div", { className: "font-medium" }, "Nutritionists"),
                        React.createElement("div", { className: "text-sm text-gray-500" }, "Dr. Richard Lee"))))),
        React.createElement("div", { className: "container mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" },
            React.createElement(Card, { className: "p-6 space-y-4 hover:shadow-lg transition-shadow" },
                React.createElement("div", { className: "w-full aspect-video bg-gray-100 rounded-2xl" }),
                React.createElement("h3", { className: "text-2xl font-semibold" }, "Consult The Best Nutrition For Your Child")),
            React.createElement(Card, { className: "p-6 space-y-4 hover:shadow-lg transition-shadow" },
                React.createElement("div", { className: "w-full aspect-video bg-gray-100 rounded-2xl" }),
                React.createElement("h3", { className: "text-2xl font-semibold" }, "Consult Diet Foods That Are Suitable For Your Body")),
            React.createElement(Card, { className: "p-6 space-y-4 hover:shadow-lg transition-shadow bg-green-100" },
                React.createElement("h3", { className: "text-2xl font-semibold" }, "Discover our supplement products"),
                React.createElement("button", { className: "p-2 rounded-full border border-gray-400" },
                    React.createElement(ArrowUpRight, { className: "w-5 h-5" })))),
        React.createElement("div", { className: "container mx-auto px-6 py-12" },
            React.createElement("div", { className: "flex justify-between items-center" },
                React.createElement("h2", { className: "text-4xl font-bold" }, "High Nutritional Organic Food"),
                React.createElement("button", { className: "bg-black text-white px-6 py-3 rounded-full hover:bg-gray-800" }, "Shop Now")))));
};
export default NutritionLandingPage;